apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiver-service
  namespace: serai-dev
  labels:
    app: receiver-service
spec:
  replicas: 1
  minReadySeconds: 30
  selector:
    matchLabels:
      app: receiver-service
  template:
    metadata:
      labels:
        app: receiver-service
    spec:
      containers:
        - name: receiver-service
          image: docker.io/kevinlwh/receiver-service:latest
          ports:
            - containerPort: 8082
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "800m"
          env:
            - name: JVM_OPTS
              value: "-Xms250m -Xmm450m"
            - name: SPRING_PROFILES_ACTIVE
              value: "kube"
            - name: SECRET_CUSTOMIZE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secret-custimize-token
                  key: token