apiVersion: v1
kind: Service
metadata:
  name: receiver-service
  namespace: serai-dev
spec:
  ports:
    - name: http
      protocol: TCP
      targetPort: 8082
      port: 80
  selector:
    app: receiver-service
