apiVersion: v1
kind: Service
metadata:
  name: feeder-service
  namespace: serai-dev
spec:
  ports:
    - name: http
      protocol: TCP
      targetPort: 8081
      port: 80
  selector:
    app: feeder-service
