apiVersion: v1
kind: Secret
metadata:
  name: secret-custimize-token
  namespace: serai-dev
type: Opaque
data:
  token: YWVmYzM2NTktZGJhZS00OTg2LWEwMTAtYzk2ODdmYWVmNzc2
#aefc3659-dbae-4986-a010-c9687faef776