spring:
  application:
    name: serai-feeder-service

server:
  port: 8081
  servlet:
    context-path: /feeder/

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
serai:
  receiver:
    url: http://localhost:8082

authentication:
  token: ${SECRET_CUSTOMIZE_TOKEN:null}