spring:
  application:
    name: serai-receiver-service

  datasource:
    url: jdbc:h2:mem:TRANS;
    username: serai
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

server:
  port: 8082
  servlet:
    context-path: /receiver/

logging:
  level:
    com.kevinlam.serai: debug

authentication:
  token: ${SECRET_CUSTOMIZE_TOKEN:invalid}
